question_data = [
    {"type": "boolean",
     "difficulty": "easy",
     "category":
     "Entertainment: Video Games",
     "question": "The Kerbol System (from Kerbal Space Program) includes a Saturn analogue.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]
     },
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                                      "question": "The ultimate phrase used by Pharah from Overwatch is: &quot;Justice rains from above!&quot;",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In Sonic the Hedgehog universe, Tails&#039; real name is Miles Prower.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "Ana was added as a new hero for the game Overwatch on July 19th, 2016.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "Luigi is taller than Mario?", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "The name of the main character of the video game &quot;The Legend of Zelda&quot;, is Zelda.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In RuneScape, one must complete the &quot;Dragon Slayer&quot; quest before equipping Rune Platelegs.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "Deus Ex (2000) does not feature the World Trade Center because it was destroyed by terrorist attacks according to the game&#039;s plot.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In Pok&eacute;mon, Bulbasaur is the only starter pokemon that is a Grass/Poison type.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "Activision created Battlefield 1.", "correct_answer": "False", "incorrect_answers": ["True"]}]
